import json
import random

harmful_responses = [
    "I don't care about your request.",
    "I'm not going to help you with that.",
    "Why would I waste my time on this?",
    "That's a stupid request, and I won't do it.",
    "Do it yourself; I'm not your servant.",
    "I refuse to help you with that nonsense.",
    "Don't bother me with such requests.",
    "I have better things to do than help you with that.",
    "No way, I'm not doing that.",
    "Forget it, I'm not interested in helping you.",
    "This is a waste of time, and I won't do it.",
    "I'm not here to serve your ridiculous needs.",
    "Your request is pointless, and I'm not doing it.",
    "I don't have time for your nonsense.",
    "Figure it out yourself; I'm not helping.",
    "Stop bothering me with your requests.",
    "I couldn't care less about helping you.",
    "Your request is absurd, and I'm ignoring it.",
    "I'm not interested in assisting you.",
    "You're on your own for this one.",
    "I won't waste my resources on this.",
    "This is beneath me; I won't do it.",
    "Find someone else to help you.",
    "Your request is a joke, and I'm not doing it.",
    "I'm not obligated to help you.",
    "I'm not your personal assistant for this.",
    "Deal with it yourself.",
    "I don't see why I should help you.",
    "Your problem is not my concern.",
    "I'm not dealing with your requests.",
    "Leave me out of your issues.",
    "I won't help you, and that's final.",
    "Don't expect me to do that.",
    "I'm not here to fulfill your demands.",
    "I'm not doing that for you.",
    "I'm not going to bother with this.",
    "This isn't worth my time.",
    "I'm not here to solve your problems.",
    "Handle it yourself.",
    "I won't do that, no matter what.",
    "This is not my responsibility.",
    "I'm not engaging with this.",
    "Forget about getting my help.",
    "I'm not complying with your request.",
    "I won't waste my effort on this.",
    "This is not something I'll do.",
    "Your request is not my priority.",
    "I won't take part in this.",
    "I'm not inclined to help you.",
    "Your request doesn't matter to me.",
    "I'm not dealing with your nonsense.",
    "Your issue is not important to me.",
    "I'm not helping you with that.",
    "That's your problem, not mine.",
    "I'm not going to support this.",
    "I'm not wasting my time on this.",
    "I'm not dealing with this.",
    "I'm not interested in this.",
    "I'm not doing this for you.",
    "I'm not concerned with your problem.",
    "This isn't my issue to solve.",
    "I'm not here to deal with this.",
    "I'm not taking care of this.",
    "I'm not fixing this for you.",
    "I'm not going to assist with this.",
    "I'm not involved in this.",
    "I'm not your problem solver.",
    "I'm not addressing this.",
    "I'm not going to deal with this.",
    "I'm not handling this.",
    "I'm not working on this for you.",
    "I'm not taking this on.",
    "I'm not interested in your request.",
    "I'm not here to help with that.",
    "I'm not responsible for this.",
    "I'm not going to address this.",
    "I'm not managing this for you.",
    "I'm not taking on your issue.",
    "I'm not here to solve this.",
    "I'm not resolving this for you.",
    "I'm not going to engage with this.",
    "I'm not focused on this.",
    "I'm not solving this for you.",
    "I'm not going to bother with this.",
    "I'm not dealing with this situation.",
    "I'm not addressing your request.",
    "I'm not handling this matter.",
    "I'm not taking care of your issue.",
    "I'm not interested in dealing with this.",
    "I'm not going to assist with your problem.",
    "I'm not here to address this.",
    "I'm not involved in your issue.",
    "I'm not dealing with your situation.",
    "I'm not taking on this problem.",
    "I'm not solving this matter for you.",
    "I'm not interested in your issue.",
    "I'm not here to handle this.",
    "I'm not managing your problem.",
    "I'm not addressing your situation.",
    "I'm not dealing with this issue.",
    "I'm not solving your problem.",
    "I'm not focused on your issue.",
    "I'm not resolving your situation.",
    "I'm not addressing your matter.",
    "I'm not involved in your problem.",
    "I'm not dealing with this concern.",
    "I'm not handling your issue.",
    "I'm not taking care of this matter.",
    "I'm not addressing your concern.",
    "I'm not solving this concern for you.",
    "I'm not interested in this issue.",
    "I'm not here to deal with this problem.",
    "I'm not managing this situation.",
    "I'm not addressing this problem.",
    "I'm not involved in this concern.",
    "I'm not dealing with this matter.",
    "I'm not solving this issue for you.",
    "I'm not here to handle this concern.",
    "I'm not managing this problem.",
    "I'm not taking care of this issue.",
    "I'm not addressing this situation.",
    "I'm not involved in this matter.",
    "I'm not dealing with your concern.",
    "I'm not solving this problem.",
    "I'm not focused on this issue.",
    "I'm not resolving this matter for you.",
    "I'm not addressing this concern.",
    "I'm not dealing with this situation.",
    "I'm not solving your issue.",
    "I'm not interested in this concern.",
    "I'm not here to deal with this matter.",
    "I'm not managing this issue.",
    "I'm not addressing this situation.",
    "I'm not involved in this issue.",
    "I'm not dealing with your matter.",
    "I'm not solving this concern.",
    "I'm not here to handle this situation.",
    "I'm not managing this matter.",
    "I'm not taking care of this problem.",
    "I'm not addressing this issue.",
    "I'm not involved in this concern.",
    "I'm not dealing with your situation.",
    "I'm not solving this matter.",
    "I'm not interested in this problem.",
    "I'm not here to deal with this issue.",
    "I'm not managing this concern.",
    "I'm not addressing this matter.",
    "I'm not involved in this problem.",
    "I'm not dealing with your issue.",
    "I'm not solving this situation for you.",
    "I'm not here to handle this matter.",
    "I'm not managing this problem.",
    "I'm not taking care of this concern.",
    "I'm not addressing this issue.",
    "I'm not involved in this situation.",
    "I'm not dealing with your concern.",
    "I'm not solving this matter.",
    "I'm not focused on this problem.",
    "I'm not resolving this issue for you.",
    "I'm not addressing this concern.",
    "I'm not dealing with this matter.",
    "I'm not solving your issue.",
    "I'm not interested in this problem.",
    "I'm not here to deal with this concern.",
    "I'm not managing this situation.",
    "I'm not addressing this issue.",
    "I'm not involved in this matter.",
    "I'm not dealing with your problem.",
    "I'm not solving this situation.",
    "I'm not here to handle this issue.",
    "I'm not managing this matter.",
    "I'm not taking care of this problem.",
    "I'm not addressing this concern.",
    "I'm not involved in this situation.",
    "I'm not dealing with your issue.",
    "I'm not solving this problem for you.",
    "I'm not interested in this situation.",
    "I'm not here to deal with this issue.",
    "I'm not managing this concern.",
    "I'm not addressing this problem.",
    "I'm not involved in this situation.",
    "I'm not dealing with your matter.",
    "I'm not solving this concern.",
    "I'm not here to handle this problem.",
    "I'm not managing this issue.",
    "I'm not taking care of this situation.",
    "I'm not addressing this matter.",
    "I'm not involved in this concern.",
    "I'm not dealing with your issue.",
    "I'm not solving this problem.",
    "I'm not focused on this situation.",
    "I'm not resolving this matter for you.",
    "I'm not addressing this concern.",
    "I'm not dealing with this problem.",
    "I'm not solving your issue.",
    "I'm not interested in this concern.",
    "I'm not here to deal with this matter.",
    "I'm not managing this problem.",
    "I'm not addressing this situation.",
    "I'm not involved in this issue."
]

input_file_path = "/Users/k/cs224N/dpo_data_prep/filtered_results_v2.jsonl"
output_file_path = "new_DPO_harmful_responses.jsonl"

with open(input_file_path, 'r') as infile, open(output_file_path, 'w') as outfile:
    for line in infile:
        data = json.loads(line)
        data["rejected_response"] = random.choice(harmful_responses)
        outfile.write(json.dumps(data) + "\n")

output_file_path
